# Generated by Django 4.2.7 on 2026-01-17 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of the application using this API key', max_length=200)),
                ('key', models.CharField(db_index=True, help_text='The API key string', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active and can be used')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this API key', null=True)),
                ('user', models.ForeignKey(help_text='User who created this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'is_active'], name='api_apikey_key_c69026_idx'), models.Index(fields=['user', 'is_active'], name='api_apikey_user_id_90f679_idx')],
            },
        ),
    ]
