"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY MUST be set in .env file - no default for security!
SECRET_KEY = config('SECRET_KEY')

# Supabase Configuration (for OAuth)
SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_ANON_KEY = config('SUPABASE_ANON_KEY', default='')
SUPABASE_SERVICE_ROLE_KEY = config('SUPABASE_SERVICE_ROLE_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG should be set in .env file (defaults to False for safety)
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # Token authentication
    'rest_framework_simplejwt',  # JWT authentication
    'drf_spectacular',  # API documentation (OpenAPI/Swagger)
    'corsheaders',
    'django_extensions',
    
    # Local apps
    'apps.recipes',
    'apps.users',
    'apps.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be early)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.api.middleware_rls.RLSAuthMiddleware',  # RLS support (PostgreSQL only)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom security middleware
    'apps.api.middleware.SecurityHeadersMiddleware',  # Add security headers
    'apps.api.middleware.RateLimitMiddleware',  # Rate limiting for API
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL Database Configuration (for Supabase)
# Set USE_SQLITE=True in .env to force SQLite for local development
# Or comment out DB_NAME to use SQLite automatically
USE_SQLITE = config('USE_SQLITE', default=False, cast=bool)

if USE_SQLITE:
    # Force SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Try PostgreSQL/Supabase configuration
    try:
        db_name = config('DB_NAME', default=None)
        if db_name and db_name.strip() and db_name != 'your-database-password-here':
            db_host = config('DB_HOST', default='localhost')
            # Check if DB_HOST contains a full connection URL (common mistake)
            # If it does, extract just the hostname
            if db_host.startswith('postgresql://') or db_host.startswith('postgres://'):
                # Extract hostname from connection string
                # Format: postgresql://user:pass@host:port/dbname
                import re
                match = re.search(r'@([^:/]+)', db_host)
                if match:
                    db_host = match.group(1)
                else:
                    # If parsing fails, use SQLite
                    db_name = None
            
            if db_name and db_name.strip() and db_name != 'your-database-password-here':
                # Use PostgreSQL configuration
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.postgresql',
                        'NAME': db_name,
                        'USER': config('DB_USER', default='postgres'),
                        'PASSWORD': config('DB_PASSWORD', default=''),
                        'HOST': db_host,
                        'PORT': config('DB_PORT', default='5432'),
                        'OPTIONS': {
                            'connect_timeout': 5,  # 5 second timeout
                        },
                    }
                }
            else:
                # Fallback to SQLite if DB_NAME is None or invalid
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.sqlite3',
                        'NAME': BASE_DIR / 'db.sqlite3',
                    }
                }
        else:
            # Fallback to SQLite for local development without database setup
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
    except Exception as e:
        # If database config fails, use SQLite fallback
        import warnings
        warnings.warn(f'Database configuration error: {e}. Falling back to SQLite.')
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads)
# For production, use Vercel Blob Storage or cloud storage
# Images will be stored via Vercel Blob API, not in local media folder
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Vercel Blob Storage Configuration (for production)
VERCEL_BLOB_STORE_ID = config('VERCEL_BLOB_STORE_ID', default='')
VERCEL_BLOB_READ_WRITE_TOKEN = config('VERCEL_BLOB_READ_WRITE_TOKEN', default='')
VERCEL_BLOB_STORE_URL = config('VERCEL_BLOB_STORE_URL', default='')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# Tell Django to use our CustomUser instead of the default User model
# IMPORTANT: This must be set BEFORE running migrations!
AUTH_USER_MODEL = 'users.CustomUser'

# CORS Settings (for frontend integration)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001,http://localhost:8000',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001',
    cast=Csv()
)

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication by default
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For web frontend
        'rest_framework.authentication.TokenAuthentication',  # For API token auth
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # For JWT auth
        'apps.api.authentication.APIKeyAuthentication',  # API Key authentication for meal planner apps
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # API Documentation (OpenAPI/Swagger)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rate Limiting (additional to middleware)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # For anonymous users
        'rest_framework.throttling.UserRateThrottle',  # For authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/hour',  # Anonymous users: 50 requests per hour
        'user': '200/hour',  # Authenticated users: 200 requests per hour
    },
}

# JWT Authentication Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# API Documentation Settings (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Recipe Sharing Platform API',
    'DESCRIPTION': 'REST API for Recipe Sharing Platform. Manage recipes, ingredients, ratings, comments, favorites, and meal plans.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    'TAGS': [
        {'name': 'recipes', 'description': 'Recipe management endpoints'},
        {'name': 'ingredients', 'description': 'Ingredient management endpoints'},
        {'name': 'users', 'description': 'User and profile endpoints'},
        {'name': 'ratings', 'description': 'Recipe rating endpoints'},
        {'name': 'comments', 'description': 'Comment endpoints'},
        {'name': 'favorites', 'description': 'Favorite recipe endpoints'},
        {'name': 'meal-plans', 'description': 'Meal planning endpoints'},
        {'name': 'authentication', 'description': 'Authentication endpoints'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 1,
        'docExpansion': 'list',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
    },
    'REDOC_UI_SETTINGS': {
        'hideDownloadButton': False,
        'hideHostname': False,
        'hideSingleRequestSample': False,
        'expandResponses': '200,201',
        'pathInMiddlePanel': True,
        'requiredPropsFirst': True,
        'sortOperationsAlphabetically': False,
        'sortTagsAlphabetically': True,
    },
}

# Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (CSP) - Enhanced XSS Protection
# CSP tells browsers what resources are allowed to load
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ["'self'"],
    'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"],  # Allow inline scripts for React
    'style-src': ["'self'", "'unsafe-inline'"],  # Allow inline styles
    'img-src': ["'self'", 'data:', 'https:', 'blob:'],  # Allow images from various sources
    'font-src': ["'self'", 'data:'],
    'connect-src': ["'self'", 'https://blob.vercel-storage.com', 'https://*.public.blob.vercel-storage.com'],
    'frame-ancestors': ["'none'"],  # Prevent clickjacking
    'base-uri': ["'self'"],
    'form-action': ["'self'"],
}

# CSRF Settings (Enhanced)
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # CSRF cookie same-site policy
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens (default)

# Session Security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript from accessing session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Session cookie same-site policy
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# Additional Security Headers
SECURE_HSTS_SECONDS = 31536000  # 1 year (only in production)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB (matches frontend validation)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit number of form fields

# Rate Limiting Configuration
RATE_LIMIT_REQUESTS = config('RATE_LIMIT_REQUESTS', default=100, cast=int)  # Requests per window
RATE_LIMIT_WINDOW = config('RATE_LIMIT_WINDOW', default=3600, cast=int)  # Window in seconds (1 hour)
