# Generated by Django 4.2.7 on 2026-01-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_mealplan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mealplan',
            new_name='recipes_mea_user_id_1c29da_idx',
            old_name='recipes_meal_user_id_7a8b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='mealplan',
            new_name='recipes_mea_date_cea93c_idx',
            old_name='recipes_meal_date_8c9d4e_idx',
        ),
    ]
